name: 'Crafting Sandbox Launcher'
description: 'Action used to generate Crafting Sandbox autolaunch URL'
author: 'Crafting Inc.'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  baseUrl:
    required: true
    description: 'the base url of the sandbox'
    default: 'https://sandboxes.cloud'
  template:
    required: true
    description: name of the template for target sandbox.
  name:
    required: false
    description: 'name of the auto launch sandbox. If not specified, a default name like <REPO>-pr-<PR-NUMBER> would be used.'
  manual:
    required: false
    description: If true, the sandbox would not be launched automatically. Default to false, which means the sandbox is automatically launched.
    default: false
  mode:
    required: false
    description: Whether to follow the PR branch and automatically update the workspace(s).
    default: auto
  checkouts:
    required: true
    description: Comma-separated string workspace:path,...
  autoFollow:
    required: false
    description: Comma-separated workspace. All these workspaces would be in auto mode
  depSnapshots:
    required: false
    description: Comma-separated string name:snapshot,...
  containerSnapshots:
    required: false
    description: Comma-separated string name:snapshot,...
  envVars:
    required: false
    description: Common-separated Github Action environment variable names.
  extraQueries:
    required: false
    description: If the built-in inputs could not meet the requirement, raw query parameters could be provided

outputs:
  url:
    description: 'generated sandbox auto launch URL'
runs:
  using: 'node16'
  main: 'dist/index.js'
